<a href="https://colab.research.google.com/github/Ashvin7510/ML/blob/main/Sea_mountain.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/mountains_vs_beaches_preferences.csv')
df

Age      Gender  Income Education_Level  Travel_Frequency  \
0       56        male   71477        bachelor                 9   
1       69        male   88740          master                 1   
2       46      female   46562          master                 0   
3       32  non-binary   99044     high school                 6   
4       60      female  106583     high school                 5   
...    ...         ...     ...             ...               ...   
52439   67      female   85325          master                 3   
52440   37      female  110346        bachelor                 7   
52441   53  non-binary   71080       doctorate                 7   
52442   40      female   75174       doctorate                 9   
52443   33  non-binary   34475          master                 6   

      Preferred_Activities  Vacation_Budget  Location  Proximity_to_Mountains  \
0                   skiing             2477     urban                     175   
1                 swimming             4777  suburban                     228   
2                   skiing             1469     urban                      71   
3                   hiking             1482     rural                      31   
4               sunbathing              516  suburban                      23   
...                    ...              ...       ...                     ...   
52439               hiking             1762  suburban                      51   
52440             swimming             1676     urban                     259   
52441             swimming             3877     urban                     164   
52442             swimming             4620  suburban                     173   
52443               hiking              928  suburban                     218   

       Proximity_to_Beaches Favorite_Season  Pets  Environmental_Concerns  \
0                       267          summer     0                       1   
1                       190            fall     0                       1   
2                       280          winter     0                       0   
3                       255          summer     1                       0   
4                       151          winter     1                       1   
...                     ...             ...   ...                     ...   
52439                   262            fall     1                       0   
52440                    84          spring     1                       0   
52441                    27            fall     0                       1   
52442                    10          summer     0                       1   
52443                   166          spring     1                       0   

       Preference  
0               1  
1               0  
2               1  
3               1  
4               0  
...           ...  
52439           1  
52440           0  
52441           0  
52442           0  
52443           0  

[52444 rows x 14 columns]

In [ ]:
df.drop(['Gender','Education_Level','Pets'],axis=1,inplace=True)
df

Age  Income  Travel_Frequency Preferred_Activities  Vacation_Budget  \
0       56   71477                 9               skiing             2477   
1       69   88740                 1             swimming             4777   
2       46   46562                 0               skiing             1469   
3       32   99044                 6               hiking             1482   
4       60  106583                 5           sunbathing              516   
...    ...     ...               ...                  ...              ...   
52439   67   85325                 3               hiking             1762   
52440   37  110346                 7             swimming             1676   
52441   53   71080                 7             swimming             3877   
52442   40   75174                 9             swimming             4620   
52443   33   34475                 6               hiking              928   

       Location  Proximity_to_Mountains  Proximity_to_Beaches Favorite_Season  \
0         urban                     175                   267          summer   
1      suburban                     228                   190            fall   
2         urban                      71                   280          winter   
3         rural                      31                   255          summer   
4      suburban                      23                   151          winter   
...         ...                     ...                   ...             ...   
52439  suburban                      51                   262            fall   
52440     urban                     259                    84          spring   
52441     urban                     164                    27            fall   
52442  suburban                     173                    10          summer   
52443  suburban                     218                   166          spring   

       Environmental_Concerns  Preference  
0                           1           1  
1                           1           0  
2                           0           1  
3                           0           1  
4                           1           0  
...                       ...         ...  
52439                       0           1  
52440                       0           0  
52441                       1           0  
52442                       1           0  
52443                       0           0  

[52444 rows x 11 columns]

In [ ]:
df.head()

Age  Income  Travel_Frequency Preferred_Activities  Vacation_Budget  \
0   56   71477                 9               skiing             2477   
1   69   88740                 1             swimming             4777   
2   46   46562                 0               skiing             1469   
3   32   99044                 6               hiking             1482   
4   60  106583                 5           sunbathing              516   

   Location  Proximity_to_Mountains  Proximity_to_Beaches Favorite_Season  \
0     urban                     175                   267          summer   
1  suburban                     228                   190            fall   
2     urban                      71                   280          winter   
3     rural                      31                   255          summer   
4  suburban                      23                   151          winter   

   Environmental_Concerns  Preference  
0                       1           1  
1                       1           0  
2                       0           1  
3                       0           1  
4                       1           0

In [ ]:
df.tail()

Age  Income  Travel_Frequency Preferred_Activities  Vacation_Budget  \
52439   67   85325                 3               hiking             1762   
52440   37  110346                 7             swimming             1676   
52441   53   71080                 7             swimming             3877   
52442   40   75174                 9             swimming             4620   
52443   33   34475                 6               hiking              928   

       Location  Proximity_to_Mountains  Proximity_to_Beaches Favorite_Season  \
52439  suburban                      51                   262            fall   
52440     urban                     259                    84          spring   
52441     urban                     164                    27            fall   
52442  suburban                     173                    10          summer   
52443  suburban                     218                   166          spring   

       Environmental_Concerns  Preference  
52439                       0           1  
52440                       0           0  
52441                       1           0  
52442                       1           0  
52443                       0           0

In [ ]:
df.isna().sum()

Age                       0
Income                    0
Travel_Frequency          0
Preferred_Activities      0
Vacation_Budget           0
Location                  0
Proximity_to_Mountains    0
Proximity_to_Beaches      0
Favorite_Season           0
Environmental_Concerns    0
Preference                0
dtype: int64

In [ ]:
df.dtypes

Age                        int64
Income                     int64
Travel_Frequency           int64
Preferred_Activities      object
Vacation_Budget            int64
Location                  object
Proximity_to_Mountains     int64
Proximity_to_Beaches       int64
Favorite_Season           object
Environmental_Concerns     int64
Preference                 int64
dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
df['Preferred_Activities']=lab.fit_transform(df['Preferred_Activities'])
df['Location']=lab.fit_transform(df['Location'])
df['Favorite_Season']=lab.fit_transform(df['Favorite_Season'])

In [ ]:
df.dtypes

Age                       int64
Income                    int64
Travel_Frequency          int64
Preferred_Activities      int64
Vacation_Budget           int64
Location                  int64
Proximity_to_Mountains    int64
Proximity_to_Beaches      int64
Favorite_Season           int64
Environmental_Concerns    int64
Preference                int64
dtype: object

In [ ]:
x=df.iloc[:,:-1].values
x

array([[   56, 71477,     9, ...,   267,     2,     1],
       [   69, 88740,     1, ...,   190,     0,     1],
       [   46, 46562,     0, ...,   280,     3,     0],
       ...,
       [   53, 71080,     7, ...,    27,     0,     1],
       [   40, 75174,     9, ...,    10,     2,     1],
       [   33, 34475,     6, ...,   166,     1,     0]])

In [ ]:
y=df.iloc[:,-1].values
y

array([1, 0, 1, ..., 0, 0, 0])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)
x_train

array([[    49,  69367,      5, ...,    134,      1,      0],
       [    50, 103956,      5, ...,    290,      3,      1],
       [    30,  91462,      3, ...,    299,      2,      1],
       ...,
       [    63,  68714,      2, ...,     43,      1,      1],
       [    20,  30887,      3, ...,      0,      3,      0],
       [    38,  78821,      2, ...,    204,      2,      1]])

In [ ]:
x_test

array([[   39, 64201,     0, ...,   286,     1,     1],
       [   21, 36359,     6, ...,    89,     1,     1],
       [   41, 45354,     8, ...,   291,     1,     0],
       ...,
       [   26, 83005,     7, ...,   245,     2,     1],
       [   34, 40751,     2, ...,    83,     1,     1],
       [   27, 89989,     6, ...,   135,     1,     1]])

In [ ]:
y_test

array([0, 0, 1, ..., 1, 0, 0])

In [ ]:
y_train

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [ ]:
x_train

array([[0.60784314, 0.49366987, 0.55555556, ..., 0.44816054, 0.33333333,
        0.        ],
       [0.62745098, 0.83956679, 0.55555556, ..., 0.96989967, 1.        ,
        1.        ],
       [0.23529412, 0.71462429, 0.33333333, ..., 1.        , 0.66666667,
        1.        ],
       ...,
       [0.88235294, 0.48713974, 0.22222222, ..., 0.14381271, 0.33333333,
        1.        ],
       [0.03921569, 0.10886218, 0.33333333, ..., 0.        , 1.        ,
        0.        ],
       [0.39215686, 0.58821176, 0.22222222, ..., 0.68227425, 0.66666667,
        1.        ]])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
knn=KNeighborsClassifier(n_neighbors=7)
bays=GaussianNB()
sv=SVC()
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
lst=[knn,bays,sv]

In [ ]:
for i in lst:
  i.fit(x_train,y_train)
  y_pred=i.predict(x_test)
  print("Model is",i)
  print(y_pred)
  print("*"*100)
  print("Confusion matrix is...........")
  print(confusion_matrix(y_test,y_pred))
  print("Accuracy score is.............")
  print(accuracy_score(y_test,y_pred))
  print("classification matrix is...........")
  print(classification_report(y_test,y_pred))

Model is KNeighborsClassifier(n_neighbors=7)
[0 0 1 ... 1 0 0]
****************************************************************************************************
Confusion matrix is...........
[[11536   312]
 [  402  3484]]
Accuracy score is.............
0.9546205669251303
classification matrix is...........
              precision    recall  f1-score   support

           0       0.97      0.97      0.97     11848
           1       0.92      0.90      0.91      3886

    accuracy                           0.95     15734
   macro avg       0.94      0.94      0.94     15734
weighted avg       0.95      0.95      0.95     15734

Model is GaussianNB()
[0 0 0 ... 1 0 0]
****************************************************************************************************
Confusion matrix is...........
[[11630   218]
 [  933  2953]]
Accuracy score is.............
0.9268463200711834
classification matrix is...........
              precision    recall  f1-score   support

           0     